### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'reduce')]

### ISSUE THREAD

**Issue by animencoding** [shopwareLabs/nextjs-shopware-starter#14]
Issue Description:
Problem
Encountering a TypeError during the execution of the shopware integration. The error message specifically states: "Cannot read properties of undefined (reading 'reduce')".

running dockware on docker-compose 
using admin-api

any idea what's causing this?

**Comment by animencoding** [comment]
i have no idea what's this

[useListing][search] Did not found any category with collection name: Summer-BBQ/Hidden-Carousel-Category

```bash

> dev
> next dev

   ▲ Next.js 14.0.0
   - Local:        http://localhost:3000
   - Environments: .env

 ✓ Ready in 2.8s
 ○ Compiling /page ...
 ✓ Compiled /page in 8.7s (1032 modules)
==> [TypeError: Cannot read properties of undefined (reading 'reduce')]
[useListing][search] Did not found any category with collection name: Summer-BBQ/Hidden-Carousel-Category
==> [TypeError: Cannot read properties of undefined (reading 'reduce')]
[useListing][search] Did not found any category with collection name: Summer-BBQ/Hidden-Category
==> [TypeError: Cannot read properties of undefined (reading 'reduce')]
==> [TypeError: Cannot read properties of undefined (reading 'reduce')]
==> [TypeError: Cannot read properties of undefined (reading 'reduce')]
 ✓ Compiled /favicon.ico/route in 495ms (37 modules)

```

**Comment by animencoding** [comment]
when i try to build i get
```
    ~/pr/shop/frontend    main !4 ?1  npm run build                                                1 ✘ 

> build
> next build

   ▲ Next.js 14.0.0
   - Environments: .env

Failed to compile.

./components/product/variant-selector.tsx
Error: 
  × Expected a semicolon
    ╭─[/home/zack/projects/astrogas/frontend/components/product/variant-selector.tsx:29:1]
 29 │   }
 30 │ 
 31 │   const combinations: Combination[] = variants.map((variant) => ({
 32 │     console.log(variant);
    ·            ─
 33 │     id: variant.id,
 34 │     availableForSale: variant.availableForSale,
 35 │     // Adds key / value pairs for each variant (ie. "color": "Black" and "size": 'M").
    ╰────

  × Expected ',', got '.'
    ╭─[/home/zack/projects/astrogas/frontend/components/product/variant-selector.tsx:29:1]
 29 │   }
 30 │ 
 31 │   const combinations: Combination[] = variants.map((variant) => ({
 32 │     console.log(variant);
    ·            ─
 33 │     id: variant.id,
 34 │     availableForSale: variant.availableForSale,
 35 │     // Adds key / value pairs for each variant (ie. "color": "Black" and "size": 'M").
    ╰────

Caused by:
    Syntax Error

Import trace for requested module:
./components/product/variant-selector.tsx
./components/product/product-description.tsx
./app/product/[...handle]/page.tsx
./node_modules/next/dist/build/webpack/loaders/next-app-loader.js?name=app%2Fproduct%2F%5B...handle%5D%2Fpage&page=%2Fproduct%2F%5B...handle%5D%2Fpage&pagePath=private-next-app-dir%2Fproduct%2F%5B...handle%5D%2Fpage.tsx&appDir=%2Fhome%2Fzack%2Fprojects%2Fastrogas%2Ffrontend%2Fapp&appPaths=%2Fproduct%2F%5B...handle%5D%2Fpage&pageExtensions=tsx&pageExtensions=ts&pageExtensions=jsx&pageExtensions=js&basePath=&assetPrefix=&nextConfigOutput=&preferredRegion=&middlewareConfig=e30%3D!./app/product/[...handle]/page.tsx?__next_edge_ssr_entry__


> Build failed because of webpack errors
   Creating an optimized production build  .%                                                                           ~/pr/ast/frontend    main !4 ?1                                                            1 ✘  23s 
 ```

**Comment by animencoding** [comment]
when i try to build i get 
```
    ~/pr/shop/frontend    main !4 ?1  npm run build                                                1 ✘ 

> build
> next build

   ▲ Next.js 14.0.0
   - Environments: .env

Failed to compile.

./components/product/variant-selector.tsx
Error: 
  × Expected a semicolon
    ╭─[/home/x/projects/shop/frontend/components/product/variant-selector.tsx:29:1]
 29 │   }
 30 │ 
 31 │   const combinations: Combination[] = variants.map((variant) => ({
 32 │     console.log(variant);
    ·            ─
 33 │     id: variant.id,
 34 │     availableForSale: variant.availableForSale,
 35 │     // Adds key / value pairs for each variant (ie. "color": "Black" and "size": 'M").
    ╰────

  × Expected ',', got '.'
    ╭─[/home/x/projects/shop/frontend/components/product/variant-selector.tsx:29:1]
 29 │   }
 30 │ 
 31 │   const combinations: Combination[] = variants.map((variant) => ({
 32 │     console.log(variant);
    ·            ─
 33 │     id: variant.id,
 34 │     availableForSale: variant.availableForSale,
 35 │     // Adds key / value pairs for each variant (ie. "color": "Black" and "size": 'M").
    ╰────

Caused by:
    Syntax Error

Import trace for requested module:
./components/product/variant-selector.tsx
./components/product/product-description.tsx
./app/product/[...handle]/page.tsx
./node_modules/next/dist/build/webpack/loaders/next-app-loader.js?name=app%2Fproduct%2F%5B...handle%5D%2Fpage&page=%2Fproduct%2F%5B...handle%5D%2Fpage&pagePath=private-next-app-dir%2Fproduct%2F%5B...handle%5D%2Fpage.tsx&appDir=%2Fhome%2Fx%2Fprojects%2Fshop%2Ffrontend%2Fapp&appPaths=%2Fproduct%2F%5B...handle%5D%2Fpage&pageExtensions=tsx&pageExtensions=ts&pageExtensions=jsx&pageExtensions=js&basePath=&assetPrefix=&nextConfigOutput=&preferredRegion=&middlewareConfig=e30%3D!./app/product/[...handle]/page.tsx?__next_edge_ssr_entry__


> Build failed because of webpack errors
   Creating an optimized production build  .%                                                                           ~/pr/ast/frontend    main !4 ?1                                                            1 ✘  23s 
   ```

**Comment by animencoding** [comment]
i gave up on deploying the frontend on my machine

and used varcel and i get this error in the log

```
 ApiClientError: Failed request
 - [Precondition Failed] No matching sales channel found.
    at (node_modules/.pnpm/@shopware+api-client@0.0.0-canary-20231024141318/node_modules/@shopware/api-client/dist/index.mjs:57:8)
    at (node_modules/.pnpm/@shopware+api-client@0.0.0-canary-20231024141318/node_modules/@shopware/api-client/dist/index.mjs:114:6)
    at (node_modules/.pnpm/ofetch@1.3.3/node_modules/ofetch/dist/shared/ofetch.00501375.mjs:254:30)
    at (node_modules/.pnpm/ofetch@1.3.3/node_modules/ofetch/dist/shared/ofetch.00501375.mjs:261:14)
    at (lib/shopware/api.ts:114:11)
    at (lib/shopware/index.ts:199:15)
    at (components/grid/three-items.tsx:46:38) {
  ok: false,
  status: 412,
  statusText: 'Precondition Failed',
  url: 'https://shop.idk.ma/store-api/product-listing/4ab73c06d90d4a5cb312209a64480d87',
  details: {
  errors: [
  {
  status: '412',
  code: 'FRAMEWORK__ROUTING_SALES_CHANNEL_NOT_FOUND',
  title: 'Precondition Failed',
  detail: 'No matching sales channel found.',
  meta: { parameters: [] },
  trace: [
  {
  file: '/var/www/html/vendor/shopware/core/Framework/Api/EventListener/Authentication/SalesChannelAuthenticationListener.php',
  line: 117,
  function: 'salesChannelNotFound',
  class: 'Shopware\\Core\\Framework\\Api\\ApiException',
  type: '::'
},
  {
  file: '/var/www/html/vendor/shopware/core/Framework/Api/EventListener/Authentication/SalesChannelAuthenticationListener.php',
  line: 84,
  function: 'getSalesChannelData',
  class: 'Shopware\\Core\\Framework\\Api\\EventListener\\Authentication\\SalesChannelAuthenticationListener',
  type: '->'
},
  {
  file: '/var/www/html/vendor/symfony/event-dispatcher/Debug/WrappedListener.php',
  line: 116,
  function: 'validateRequest',
  class: 'Shopware\\Core\\Framework\\Api\\EventListener\\Authentication\\SalesChannelAuthenticationListener',
  type: '->'
},
  {
  file: '/var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php',
  line: 206,
  function: '__invoke',
  class: 'Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener',
  type: '->'
},
  {
  file: '/var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php',
  line: 56,
  function: 'callListeners',
  class: 'Symfony\\Component\\EventDispatcher\\EventDispatcher',
  type: '->'
},
  {
  file: '/var/www/html/vendor/shopware/core/Content/Flow/Dispatching/FlowDispatcher.php',
  line: 47,
  function: 'dispatch',
  class: 'Symfony\\Component\\EventDispatcher\\EventDispatcher',
  type: '->'
},
  {
  file: '/var/www/html/vendor/shopware/core/Framework/Webhook/WebhookDispatcher.php',
  line: 70,
  function: 'dispatch',
  class: 'Shopware\\Core\\Content\\Flow\\Dispatching\\FlowDispatcher',
  type: '->'
},
  {
  file: '/var/www/html/vendor/shopware/core/Framework/Event/NestedEventDispatcher.php',
  line: 31,
  function: 'dispatch',
  class: 'Shopware\\Core\\Framework\\Webhook\\WebhookDispatcher',
  type: '->'
},
  {
  file: '/var/www/html/vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php',
  line: 127,
  function: 'dispatch',
  class: 'Shopware\\Core\\Framework\\Event\\NestedEventDispatcher',
  type: '->'
},
  {
  file: '/var/www/html/vendor/symfony/http-kernel/HttpKernel.php',
  line: 166,
  function: 'dispatch',
  class: 'Symfony\\Component\\EventDispatcher\\Debug\\TraceableEventDispatcher',
  type: '->'
},
  {
  file: '/var/www/html/vendor/symfony/http-kernel/HttpKernel.php',
  line: 76,
  function: 'handleRaw',
  class: 'Symfony\\Component\\HttpKernel\\HttpKernel',
  type: '->'
},
  {
  file: '/var/www/html/vendor/shopware/core/Framework/Adapter/Kernel/HttpKernel.php',
  line: 56,
  function: 'handle',
  class: 'Symfony\\Component\\HttpKernel\\HttpKernel',
  type: '->'
},
  {
  file: '/var/www/html/vendor/symfony/http-kernel/HttpCache/SubRequestHandler.php',
  line: 86,
  function: 'handle',
  class: 'Shopware\\Core\\Framework\\Adapter\\Kernel\\HttpKernel',
  type: '->'
},
  {
  file: '/var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php',
  line: 460,
  function: 'handle',
  class: 'Symfony\\Component\\HttpKernel\\HttpCache\\SubRequestHandler',
  type: '::'
},
  {
  file: '/var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php',
  line: 262,
  function: 'forward',
  class: 'Symfony\\Component\\HttpKernel\\HttpCache\\HttpCache',
  type: '->'
},
  {
  file: '/var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php',
  line: 276,
  function: 'pass',
  class: '
  
```

```
Details: {
  errors: [
  {
  status: '412',
  code: 'FRAMEWORK__ROUTING_SALES_CHANNEL_NOT_FOUND',
  title: 'Precondition Failed',
  detail: 'No matching sales channel found.',
  meta: { parameters: [] },
  trace: [
  {
  file: '/var/www/html/vendor/shopware/core/Framework/Api/EventListener/Authentication/SalesChannelAuthenticationListener.php',
  line: 117,
  function: 'salesChannelNotFound',
  class: 'Shopware\\Core\\Framework\\Api\\ApiException',
  type: '::'
},
  {
  file: '/var/www/html/vendor/shopware/core/Framework/Api/EventListener/Authentication/SalesChannelAuthenticationListener.php',
  line: 84,
  function: 'getSalesChannelData',
  class: 'Shopware\\Core\\Framework\\Api\\EventListener\\Authentication\\SalesChannelAuthenticationListener',
  type: '->'
},
  {
  file: '/var/www/html/vendor/symfony/event-dispatcher/Debug/WrappedListener.php',
  line: 116,
  function: 'validateRequest',
  class: 'Shopware\\Core\\Framework\\Api\\EventListener\\Authentication\\SalesChannelAuthenticationListener',
  type: '->'
},
  {
  file: '/var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php',
  line: 206,
  function: '__invoke',
  class: 'Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener',
  type: '->'
},
  {
  file: '/var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php',
  line: 56,
  function: 'callListeners',
  class: 'Symfony\\Component\\EventDispatcher\\EventDispatcher',
  type: '->'
},
  {
  file: '/var/www/html/vendor/shopware/core/Content/Flow/Dispatching/FlowDispatcher.php',
  line: 47,
  function: 'dispatch',
  class: 'Symfony\\Component\\EventDispatcher\\EventDispatcher',
  type: '->'
},
  {
  file: '/var/www/html/vendor/shopware/core/Framework/Webhook/WebhookDispatcher.php',
  line: 70,
  function: 'dispatch',
  class: 'Shopware\\Core\\Content\\Flow\\Dispatching\\FlowDispatcher',
  type: '->'
},
  {
  file: '/var/www/html/vendor/shopware/core/Framework/Event/NestedEventDispatcher.php',
  line: 31,
  function: 'dispatch',
  class: 'Shopware\\Core\\Framework\\Webhook\\WebhookDispatcher',
  type: '->'
},
  {
  file: '/var/www/html/vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php',
  line: 127,
  function: 'dispatch',
  class: 'Shopware\\Core\\Framework\\Event\\NestedEventDispatcher',
  type: '->'
},
  {
  file: '/var/www/html/vendor/symfony/http-kernel/HttpKernel.php',
  line: 166,
  function: 'dispatch',
  class: 'Symfony\\Component\\EventDispatcher\\Debug\\TraceableEventDispatcher',
  type: '->'
},
  {
  file: '/var/www/html/vendor/symfony/http-kernel/HttpKernel.php',
  line: 76,
  function: 'handleRaw',
  class: 'Symfony\\Component\\HttpKernel\\HttpKernel',
  type: '->'
},
  {
  file: '/var/www/html/vendor/shopware/core/Framework/Adapter/Kernel/HttpKernel.php',
  line: 56,
  function: 'handle',
  class: 'Symfony\\Component\\HttpKernel\\HttpKernel',
  type: '->'
},
  {
  file: '/var/www/html/vendor/symfony/http-kernel/HttpCache/SubRequestHandler.php',
  line: 86,
  function: 'handle',
  class: 'Shopware\\Core\\Framework\\Adapter\\Kernel\\HttpKernel',
  type: '->'
},
  {
  file: '/var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php',
  line: 460,
  function: 'handle',
  class: 'Symfony\\Component\\HttpKernel\\HttpCache\\SubRequestHandler',
  type: '::'
},
  {
  file: '/var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php',
  line: 262,
  function: 'forward',
  class: 'Symfony\\Component\\HttpKernel\\HttpCache\\HttpCache',
  type: '->'
},
  {
  file: '/var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php',
  line: 276,
  function: 'pass',
  class: 'Symfony\\Component\\HttpKernel\\HttpCache\\HttpCache',
  type: '->'
},
  {
  file: '/var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php',
  line: 204,
  function: 'invalidate',
  class: 'Symfony\\Component\\HttpKernel\\HttpCache\\HttpCache',
  type: '->'
},
  {
  file: '/var/www/html/vendor/shopware/core/Framework/Adapter/Kernel/HttpCacheKernel.php',
  line: 65,
  function: 'handle',
  class: 'Symfony\\Component\\HttpKernel\\HttpCache\\HttpCache',
  type: '->'
},
  {
  file: '/va
```

**Comment by animencoding** [comment]
i gave up on deploying on my local machine and used vercel now i get this error 
is this frontend actually ready for people to use or just some facade i really need to know if i'm able to use shopware with next commerce 
```
  errors: [
  {
  status: '404',
  code: 'PRODUCT__CATEGORY_NOT_FOUND',
  title: 'Not Found',
  detail: 'Could not find category with id "ff7bf3c59f1342a685844fbf8fdf9dc8"',
  meta: {
  parameters: {
  entity: 'category',
  field: 'id',
  value: 'ff7bf3c59f1342a685844fbf8fdf9dc8'
}
```

**Comment by animencoding** [comment]
Solution Edit:
```tsx
components/carousel.tsx 
components/grid/three-items.tsx
```

Change the hard-coded ID with your own (you can obtain it from the URL in the admin panel).

Had more issues with Shopware that I decided to switch completely. I advise anyone reading this to look for alternatives, since support for Shopware is almost nonexistent.
